### PR TITLE
Implemented Pixel shift

### PR DESCRIPTION
**Pull request by ThijsIllimited**

### CODE REVIEW

**Comment by jankoslavic** [comment]
Thanks @ThijsIllimited ! I have a few suggestions. In case `pixel_shift=False` the performance should not be impacted. 

For example, here: https://github.com/ladisk/pyidi/blob/f2448c3e0ae79028f125881945aacbf39f276908/pyidi/methods/_simplified_optical_flow.py#L76C13-L76C21
is there a need to allocate an array of zeros? I guess in case of `pixel_shift=False` the code would work nicely if it would be `self.delta_0 = 0`.

Further, the code would be cleaner if the whole pixel shifting would be handled within the already reserved method `def pixel_shift`. Do you think you could handle it?

thanks

**Comment by ThijsIllimited** [comment]
Thanks for the feedback. I'm working on it with Klemen

**Comment by jankoslavic** [comment]
@klemengit can we accept this PR?

**Review by klemengit — APPROVED** [review]
I have looked over the changes.
The pixel shifting functionality is correctly implemented according to the [The subpixel resolution of optical-flow-based modal analysis](http://dx.doi.org/10.1016/j.ymssp.2016.11.009) article.

**Pull request merged**
